package com.myspace.gradeprojectexample;
import com.myspace.gradeprojectexample.Student;
/**
 * This class was automatically generated by the data modeler tool.
 */

import java.util.HashMap;
import java.util.Map;

import org.drools.core.process.instance.WorkItemHandler;
import org.kie.api.runtime.process.WorkItem;
import org.kie.api.runtime.process.WorkItemManager;

public class MyServiceHandler implements WorkItemHandler{

	public void executeWorkItem(WorkItem workItem, WorkItemManager manager) {
		
		Student st=(Student)workItem.getParameter("stud");
		int student_marks=st.getMarks();
		String grade="";
		if(student_marks>80)
		    grade="A";
		else if(student_marks<=80 && student_marks>60)
		    grade="B";
		else if(student_marks<=60 && student_marks>40)
		    grade="C";
		else
		    grade="fail";
		st.setGrade(grade);
	    Map<String, Object> map=new HashMap<String,Object>();
		map.put("stud",st);
		manager.completeWorkItem(workItem.getId(), map);
		
	}

	public void abortWorkItem(WorkItem workItem, WorkItemManager manager) {
		// TODO Auto-generated method stub
		
	}




}